### ISSUE TITLE
Use appEvents to emit event when remoteUrlWorker finished processing a Mediarecord

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction-file-collections#22]
Catalog products need to know mediaUrls during publish.
If publish was run on a product before remoteUrlWorker finished retriving the image, the Catalog product would display a blank product image.

Currently, there is no way for the publishing process to know wether these images exist already. In a probably common API-driven use case, `RemoteUrlWorker` would retrieve the images, and there would be no manual publishing process.

This could be solved using appEvents:
`appEvents.emit("afterMediaFromRemoteURLStored", doc._id, { productId, variantId })`

A custom plugin could then listen to that event and make sure that the Catalog product is updated properly, by triggering a publish ( or using a different, more efficient way to update the catalog media)

**Comment by aldeed** [comment]
Requiring all media changes to be explicitly published to the catalog was an intentional design choice, so I don't think auto-publishing media after it's stored is correct, but preventing the product from being published until the media is fully available does make sense.

Some installations have used a custom function type "isReadyToPublish" to allow any plugin to block publication of a catalog product if some information is not yet ready. I think we may want to pull this idea into the core app. Then the `files` plugin could return `false` for any product that doesn't have all of the necessary media fully uploaded yet.

**Comment by janus-reith** [comment]
Closing this, as I Implemented a callback when I did the demeteorization part that is used to create a job which converts the image. The considerations here are therefore mostly obsolete as we had no proper way of knowing outside the library at which stage an image upload was. Now discussion regarding the need for a separate `appEvent` could happen in the main reaction repo instead.
